name: Generate a build and push to build branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create folder of production
        run: mkdir public_html

      - name: navigate to public_html and create src folder
        run: cd public_html && mkdir src

      - name: Copy dist html file into public_html
        run: cp dist/index.html public_html

      - name: Copy dist assets folder into public_html/src
        run: cp -r dist/assets public_html/src

      - name: Copy images folder into public_html/src/assets
        run: cp -r src/assets/images public_html/src/assets

      - name: List contents of public_html
        run: ls public_html

      - name: Push to build branch
        uses: ad-m/github-push-action@master
        with:
          branch: build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          directory: public_html